name: Deploy Vite Frontend to Azure Storage

on:
  push:
    branches:
      - main # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust based on your project

      - name: Install Dependencies
        run: npm ci # Ensures a clean install

      - name: Build Vite App
        run: npm run build # This generates the 'dist/' folder

      - name: List Build Files for Debugging
        run: ls -la dist # Ensure 'dist/' exists before deployment

      - name: Deploy to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination '$web' \
              --source dist \
              --overwrite
